/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'getCoins' : ActorMethod<[], bigint>,
  'getHighestChapter' : ActorMethod<[], bigint>,
  'getSelectedHero' : ActorMethod<[], string>,
  'getTotalKills' : ActorMethod<[], bigint>,
  'getTotalRuns' : ActorMethod<[], bigint>,
  'getUpgradeLevel' : ActorMethod<[string], bigint>,
  'isHeroUnlocked' : ActorMethod<[string], boolean>,
  'purchaseUpgrade' : ActorMethod<[string], undefined>,
  'recordRunEnd' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'selectHero' : ActorMethod<[string], undefined>,
  'unlockHero' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];