/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getCoins' : IDL.Func([], [IDL.Nat], ['query']),
  'getHighestChapter' : IDL.Func([], [IDL.Nat], ['query']),
  'getSelectedHero' : IDL.Func([], [IDL.Text], ['query']),
  'getTotalKills' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalRuns' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpgradeLevel' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isHeroUnlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'purchaseUpgrade' : IDL.Func([IDL.Text], [], []),
  'recordRunEnd' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'selectHero' : IDL.Func([IDL.Text], [], []),
  'unlockHero' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getCoins' : IDL.Func([], [IDL.Nat], ['query']),
    'getHighestChapter' : IDL.Func([], [IDL.Nat], ['query']),
    'getSelectedHero' : IDL.Func([], [IDL.Text], ['query']),
    'getTotalKills' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalRuns' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpgradeLevel' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isHeroUnlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'purchaseUpgrade' : IDL.Func([IDL.Text], [], []),
    'recordRunEnd' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'selectHero' : IDL.Func([IDL.Text], [], []),
    'unlockHero' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };